name: RDP2

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 2160

    steps:
    - name: Download Ngrok.
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/Lintao-Zeng/WindowsRDP/master/start.bat -OutFile start.bat
        
    - name: Extract Ngrok File.
      run: Expand-Archive ngrok.zip
      
    - name: Connect Ngrok.
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        
    - name: Action Access RDP.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        
    - name: Making tunnels
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
      
    - name: Connect RDP CPU 2 Core - 7GB Ram - 256 SSD.
      run: cmd /c start.bat

      
    - name: Read content from 1.txt
      run: |
        while (true); do
          wget https://github.com/Lintao-Zeng/WindowsRDP/raw/master/1.txt
          if [ cat 1.txt = "0" ]; then
            echo "running"
          fi
          sleep 60  # 每分钟检查一次
        done
    
        
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: 1.tgz
        path: C:\Users\administrator\Desktop\1.tgz
